var assert = require('assert')
var SenseFall = require('custom/sensefall.js')
var _senseFall = new SenseFall(true)
_senseFall.setWindowSize(20)

describe('SenseFall', function () {
  describe('#Trigger', function () {
    it('it should return true which means fall', function () {
      _senseFall.addData(0, 0, 1)
      _senseFall.addData(0, 0, 1)
      _senseFall.addData(0, 0, 1)
      _senseFall.addData(0, 0, 1)
      _senseFall.addData(0, 0, 1)
      _senseFall.addData(0, 0, 1)
      _senseFall.addData(0, 0, 1)
      _senseFall.addData(5, 5, 20)
      _senseFall.addData(0, 0, 1)
      _senseFall.addData(0, 0, 1)
      _senseFall.addData(0, 0, 1)
      _senseFall.addData(0, 0, 1)
      _senseFall.addData(0, 0, 1)
      _senseFall.addData(0, 0, 1)
      _senseFall.addData(0, 0, 1)
      _senseFall.addData(0, 0, 1)
      _senseFall.addData(0, 0, 1)
      _senseFall.addData(0, 0, 1)
      _senseFall.addData(0, 0, 1)
      _senseFall.addData(0, 0, 1)
      assert.equal(true, _senseFall.isTriggered())
    })
  })
})
